table 'Work info'
	lineageTag: 0509c7b6-da97-47d0-8b59-359494d7c415

	column Topic
		dataType: string
		lineageTag: f8849c01-7e1d-45f9-99a3-7a510e1871a3
		summarizeBy: none
		sourceColumn: Topic
		sortByColumn: 'Topic ID'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sub-topic
		dataType: string
		lineageTag: bb00d796-4f16-40be-8e2f-62348aa36503
		summarizeBy: none
		sourceColumn: Sub-topic

		annotation SummarizationSetBy = Automatic

	column 'Frequency rank value'
		dataType: int64
		formatString: 0
		lineageTag: eb7c2a93-9dbe-40da-9e18-0fe099098765
		summarizeBy: none
		sourceColumn: Frequency rank value

		annotation SummarizationSetBy = User

	column 'Sub-topic ID'
		dataType: double
		isHidden
		lineageTag: d4e9de72-d7ab-47f2-81d2-94e66c8db5da
		summarizeBy: none
		sourceColumn: Sub-topic ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Topic ID'
		dataType: double
		isHidden
		lineageTag: 818e3ef3-3cdb-491c-8f58-b004a76a4816
		summarizeBy: none
		sourceColumn: Topic ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Visualisation & Analysis'
		dataType: int64
		formatString: 0
		lineageTag: 89a6f49b-7f30-49c2-b09c-bafca75a3659
		summarizeBy: none
		sourceColumn: Visualisation & Analysis

		annotation SummarizationSetBy = User

	column 'Data processing & other'
		dataType: int64
		formatString: 0
		lineageTag: 263908a8-e65b-4003-b8e4-2f054c383828
		summarizeBy: none
		sourceColumn: Data processing & other

		annotation SummarizationSetBy = User

	column 'Tech image'
		dataType: string
		lineageTag: 61288976-b911-40cb-91d9-b8e6f17ee443
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Tech image

		annotation SummarizationSetBy = Automatic

	column 'Frequency rank'
		dataType: string
		lineageTag: 26d5e2ab-e0e1-44dc-9456-fa090b905656
		summarizeBy: none
		sourceColumn: Frequency rank

		annotation SummarizationSetBy = Automatic

	partition 'Work info' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/BTHiggins/PowerBI/main/Data/Work%20info.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Topic", type text}, {"Sub-topic", type text}, {"Percent", Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Topic", Order.Ascending}, {"Percent", Order.Descending}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Sorted Rows", "Custom", each if [#"Sub-topic"] = "Power BI" then 1 else if [#"Sub-topic"] = "Python" then 2 else if [#"Sub-topic"] = "Excel" then 3 else if [#"Sub-topic"] = "R" then 4 else if [#"Sub-topic"] = "SQL" then 5 else if [#"Sub-topic"] = "Python - Object Oriented" then 1 else if [#"Sub-topic"] = "Power BI - Optimisations" then 2 else if [#"Sub-topic"] = "SQL - Skills refresher" then 3 else if [#"Sub-topic"] = "Power BI Report Development" then 1 else if [#"Sub-topic"] = "Analytical support" then 2 else if [#"Sub-topic"] = "Data enhancement" then 3 else if [#"Sub-topic"] = "Data quality checking" then 4 else if [#"Sub-topic"] = "Training others" then 5 else if [#"Sub-topic"] = "Hanging out with friends" then 1 else if [#"Sub-topic"] = "Gaming" then 2 else if [#"Sub-topic"] = "Tending to freeloaders (cats)" then 3 else if [#"Sub-topic"] = "Music" then 4 else null, type number),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Sub-topic ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Topic", "Sub-topic ID", "Sub-topic", "Percent", "Visualisation & Analysis", "Data processing & Other"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Reordered Columns", "Topic ID", each if [Topic] = "Current job tech usage" then 1 else if [Topic] = "Current learning focus" then 3 else if [Topic] = "Current tasks" then 2 else if [Topic] = "Free time" then 4 else null, type number),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Conditional Column1",{"Topic ID", "Topic", "Sub-topic ID", "Sub-topic", "Visualisation & Analysis", "Data processing & Other", "Percent", "Tech image"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns1",{{"Visualisation & Analysis", Int64.Type}, {"Data processing & Other", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Percent", "Frequency Rank Value"}}),
				    #"Added Conditional Column2" = Table.AddColumn(#"Renamed Columns1", "Frequency Rank", each if [#"Sub-topic"] = "Power BI" then 1 else if [#"Sub-topic"] = "Python" then 2 else if [#"Sub-topic"] = "Excel" then 3 else if [#"Sub-topic"] = "R" then 4 else if [#"Sub-topic"] = "SQL" then 5 else if [#"Sub-topic"] = "Python - Object Oriented" then 1 else if [#"Sub-topic"] = "SQL - Skills refresher" then 2 else if [#"Sub-topic"] = "Power BI - Optimisations" then 3 else if [#"Sub-topic"] = "Power BI Report Development" then 1 else if [#"Sub-topic"] = "Data enhancement" then 2 else if [#"Sub-topic"] = "Analytical support" then 3 else if [#"Sub-topic"] = "Data quality checking" then 4 else if [#"Sub-topic"] = "Training others" then 5 else if [#"Sub-topic"] = "Hanging out with friends" then 1 else if [#"Sub-topic"] = "Gaming" then 2 else if [#"Sub-topic"] = "Tending to freeloaders (cats)" then 3 else if [#"Sub-topic"] = "Music" then 4 else null, type number),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column2",{{"Frequency Rank", type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type2",{{"Frequency Rank", "Frequency rank"}, {"Frequency Rank Value", "Frequency rank value"}, {"Data processing & Other", "Data processing & other"}})
				in
				    #"Renamed Columns2"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

